root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["bin", "tmp", "vendor", "docs", "coverage"]
  exclude_file = []
  exclude_regex = [".*\\.out$", ".*\\.test$", ".*\\.exe$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "env", "yaml", "yml", "toml", "json"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "green"
  runner = "cyan"
  watcher = "blue"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
