linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - misspell
    - revive
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: true
  gosec:
    excludes:
      - G107

run:
  deadline: 5m
  tests: true
