import { defineConfig } from "orval";
import dotenv from "dotenv";

dotenv.config();

export default defineConfig({
  api: {
    output: {
      mode: "tags-split",
      target: "./gen/api/generated.ts",
      schemas: "./gen/api/models",
      client: "axios",
      mock: false,
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: "./lib/axios/fetcher.ts",
          name: "orvalFetcher",
        },
        operations: {
          // Global operation overrides
          // transformOperationName: (operation: string) => {
          //   return operation.replace(/Controller/g, "");
          // },
        },
        header: (info) => [
          `Generated by Orval v7.0.0`,
          `Date: ${new Date().toISOString()}`,
          `Title: ${info.title}`,
          `Version: ${info.version}`,
        ],
      },
    },
    input: {
      target: process.env.ORVAL_OPENAPI_JSON_URL || "./openapi.json", // or your OpenAPI spec URL
      validation: false,
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
  },
});
