import { defineConfig } from "orval";
import dotenv from "dotenv";

dotenv.config();

export default defineConfig({
  api: {
    output: {
      mode: "single",
      target: "./gen/api/index.ts",
      schemas: "./gen/schema",
      client: "axios",
      mock: false,
      clean: true,
      prettier: true,
      override: {
        header: (info) => [
          `Generated by Orval v7.0.0`,
          `Date: ${new Date().toISOString()}`,
          `Title: ${info.title}`,
          `Version: ${info.version}`,
        ],
        // Don't include schemas in the API file since they're in a separate file
        schemas: {
          // Override to prevent schema generation in the API file
        },
      },
    },
    input: {
      target: process.env.ORVAL_OPENAPI_JSON_URL,
      validation: false,
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
  },
  "api-react-query": {
    output: {
      mode: "single",
      target: "./gen/hook/index.ts",
      schemas: "./gen/schema",
      client: "react-query",
      mock: false,
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: "./lib/axios/fetcher.ts",
          name: "orvalFetcher",
        },
        header: (info) => [
          `Generated by Orval v7.0.0`,
          `Date: ${new Date().toISOString()}`,
          `Title: ${info.title}`,
          `Version: ${info.version}`,
        ],
        // React Query specific configuration for suspense
        query: {
          useSuspenseQuery: true, // ← this enables useSuspenseQuery
        },
      },
    },
    input: {
      target: process.env.ORVAL_OPENAPI_JSON_URL,
      validation: false,
    },
    hooks: {
      afterAllFilesWrite: "prettier --write",
    },
  },
});
