"""Fix ID column types for roles table

Revision ID: 5e37077d2526
Revises: a83659e3997a
Create Date: 2025-11-26 15:21:58.590651

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e37077d2526"
down_revision: Union[str, Sequence[str], None] = "a83659e3997a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import sqlite3

    from sqlalchemy.exc import OperationalError

    # Use batch operations for SQLite compatibility
    with op.batch_alter_table("roles", schema=None) as batch_op:
        # Update title column type
        batch_op.alter_column(
            "title",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=50),
            existing_nullable=False,
        )
        # Update description column type
        batch_op.alter_column(
            "description", existing_type=sa.TEXT(), type_=sa.String(length=250), nullable=True
        )

        # Try to create the unique constraint, but ignore if it already exists
        try:
            batch_op.create_unique_constraint("uq_roles_title", ["title"])
        except OperationalError:
            # Constraint likely already exists, continue
            pass

    # Try to create the index separately, but ignore if it already exists
    try:
        op.create_index("ix_roles_id", "roles", ["id"], unique=False)
    except OperationalError:
        # Index likely already exists, continue
        pass

    # Update the user_roles table to match role id type
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.alter_column(
            "role_id",
            existing_type=sa.NUMERIC(),
            type_=sa.String(length=36),
            existing_nullable=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_roles",
        "role_id",
        existing_type=sa.String(length=36),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "roles", type_="unique")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.create_index(op.f("ix_roles_title"), "roles", ["title"], unique=1)
    op.alter_column(
        "roles", "description", existing_type=sa.String(length=250), type_=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "roles",
        "title",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "roles",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
