#!/usr/bin/env python3
"""
Authorization Manager CLI

This script provides a CLI interface to manage permissions and policies stored in JSON files,
and synchronizes them with corresponding Python Enum files used in the application.
"""

import json
import uuid
from datetime import datetime
from pathlib import Path


class AuthManager:
    def __init__(self):
        # Define file paths
        self.permissions_json_path = Path("statics/permissions.json")
        self.policies_json_path = Path("statics/policies.json")
        self.permissions_py_path = Path("app/utils/auth/permission.py")
        self.policies_py_path = Path("app/utils/auth/policies.py")

        # Create directories if they don't exist
        self.permissions_json_path.parent.mkdir(parents=True, exist_ok=True)
        self.permissions_py_path.parent.mkdir(parents=True, exist_ok=True)

        # Load data from JSON files
        self.permissions = self.load_permissions()
        self.policies = self.load_policies()

    def load_permissions(self):
        """Load permissions from JSON file."""
        if self.permissions_json_path.exists():
            with open(self.permissions_json_path, "r") as f:
                return json.load(f)
        else:
            # Create default file if it doesn't exist
            default_data = []
            self.save_permissions(default_data)
            return default_data

    def load_policies(self):
        """Load policies from JSON file."""
        if self.policies_json_path.exists():
            with open(self.policies_json_path, "r") as f:
                return json.load(f)
        else:
            # Create default file if it doesn't exist
            default_data = []
            self.save_policies(default_data)
            return default_data

    def save_permissions(self, data):
        """Save permissions to JSON file."""
        with open(self.permissions_json_path, "w") as f:
            json.dump(data, f, indent=2)
        self.permissions = data

    def save_policies(self, data):
        """Save policies to JSON file."""
        with open(self.policies_json_path, "w") as f:
            json.dump(data, f, indent=2)
        self.policies = data

    def generate_id(self):
        """Generate a unique ID."""
        return str(uuid.uuid4())

    def format_title_for_enum(self, title):
        """Format title to be compatible with Python enum naming."""
        # Split by ':' first
        parts = title.split(":")
        formatted_parts = []
        for part in parts:
            # Replace hyphens with underscores temporarily for word separation
            part = part.replace("-", "_")
            # Split by underscores to get individual words, then capitalize each and join
            words = part.split("_")
            # Convert to PascalCase by capitalizing the first letter of each word
            pascal_case_word = "".join(word.capitalize() for word in words)
            formatted_parts.append(pascal_case_word)
        return "_".join(formatted_parts)

    def generate_permissions_py(self):
        """Generate the permissions Python file."""
        content = '''"""
DO NOT EDIT THIS FILE

This file contents are generated by
the corresponding CLI tools
"""'''
        content += "\n\nfrom enum import Enum\n\n\nclass Permission(Enum):\n"

        if self.permissions:
            for perm in self.permissions:
                title = perm["title"]
                perm_id = perm["id"]
                enum_name = self.format_title_for_enum(title)
                content += f'    {enum_name} = "{perm_id}"\n'
        else:
            content += "    # No permissions defined\n"

        with open(self.permissions_py_path, "w") as f:
            f.write(content)

    def generate_policies_py(self):
        """Generate the policies Python file."""
        content = '''"""
DO NOT EDIT THIS FILE

This file contents are generated by
the corresponding CLI tools
"""'''
        content += "\n\nfrom enum import Enum\n\n\nclass Policy(Enum):\n"

        if self.policies:
            for policy in self.policies:
                title = policy["title"]
                policy_id = policy["id"]
                # Convert policy title to enum format (e.g., "users:create_default" -> "UsersCreateDefault")
                # Replace non-alphanumeric characters with spaces, then capitalize each word
                # Handle special case for policies starting with "users:"
                if title.startswith("users:"):
                    # Format like "users:create_default" -> "UsersCreateDefault"
                    parts = (
                        title[6:]
                        .replace("-", " ")
                        .replace(":", " ")
                        .replace("_", " ")
                        .split()
                    )  # Skip "users:" part
                    enum_name = "Users" + "".join(word.capitalize() for word in parts)
                else:
                    enum_name = "".join(
                        word.capitalize()
                        for word in title.replace("-", " ")
                        .replace(":", " ")
                        .replace("_", " ")
                        .split()
                    )

                content += f'    {enum_name} = "{policy_id}"\n'
        else:
            content += "    # No policies defined\n"

        with open(self.policies_py_path, "w") as f:
            f.write(content)

    def sync_python_files(self):
        """Synchronize the JSON files with the Python enum files."""
        self.generate_permissions_py()
        self.generate_policies_py()
        print("Python files synchronized successfully!")

    # Permissions operations
    def read_all_permissions(self):
        """Display all permissions."""
        print("\n--- All Permissions ---")
        if not self.permissions:
            print("No permissions found.")
            return
        for perm in self.permissions:
            print(f"ID: {perm['id']}")
            print(f"Title: {perm['title']}")
            print(f"Description: {perm['description']}")
            print(f"Policies: {perm['policies']}")
            print(f"Created At: {perm['created_at']}")
            print(f"Updated At: {perm['updated_at']}")
            print("---")

    def read_permission_by_title(self, title):
        """Find and display a specific permission by title."""
        for perm in self.permissions:
            if perm["title"] == title:
                print("\n--- Permission Details ---")
                print(f"ID: {perm['id']}")
                print(f"Title: {perm['title']}")
                print(f"Description: {perm['description']}")
                print(f"Policies: {perm['policies']}")
                print(f"Created At: {perm['created_at']}")
                print(f"Updated At: {perm['updated_at']}")
                return perm
        print(f"No permission found with title: {title}")
        return None

    def create_permission(self, title, description, policy_ids=None):
        """Create a new permission."""
        if policy_ids is None:
            policy_ids = []

        # Validate that policy IDs exist
        for pid in policy_ids:
            if not any(p["id"] == pid for p in self.policies):
                print(f"Error: Policy with ID {pid} does not exist!")
                return False

        current_time = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
        new_permission = {
            "id": self.generate_id(),
            "title": title,
            "description": description,
            "policies": policy_ids,
            "created_at": current_time,
            "updated_at": current_time,
        }

        self.permissions.append(new_permission)
        self.save_permissions(self.permissions)
        self.sync_python_files()
        print(
            f"Permission '{title}' created successfully with ID: {new_permission['id']}"
        )
        return True

    def update_permission(self, title, new_title=None, description=None):
        """Update an existing permission (title and description only)."""
        for i, perm in enumerate(self.permissions):
            if perm["title"] == title:
                if new_title is not None:
                    perm["title"] = new_title
                if description is not None:
                    perm["description"] = description

                perm["updated_at"] = datetime.now().strftime(
                    "%Y-%m-%dT%H:%M:%SZ"
                )  # Update timestamp
                self.permissions[i] = perm
                self.save_permissions(self.permissions)
                self.sync_python_files()
                print(f"Permission with title '{title}' updated successfully.")
                return True

        print(f"No permission found with title: {title}")
        return False

    def update_permission_policies(self, perm_title, policy_ids):
        """Update the policies associated with a permission."""
        for i, perm in enumerate(self.permissions):
            if perm["title"] == perm_title:
                # Validate that policy IDs exist
                for pid in policy_ids:
                    if not any(p["id"] == pid for p in self.policies):
                        print(f"Error: Policy with ID {pid} does not exist!")
                        return False
                perm["policies"] = policy_ids

                perm["updated_at"] = datetime.now().strftime(
                    "%Y-%m-%dT%H:%M:%SZ"
                )  # Update timestamp
                self.permissions[i] = perm
                self.save_permissions(self.permissions)
                self.sync_python_files()
                print(f"Policies for permission '{perm_title}' updated successfully.")
                return True

        print(f"No permission found with title: {perm_title}")
        return False

    def delete_permission(self, title):
        """Delete a permission by title."""
        for i, perm in enumerate(self.permissions):
            if perm["title"] == title:
                del self.permissions[i]
                self.save_permissions(self.permissions)
                self.sync_python_files()
                print(f"Permission with title '{title}' deleted successfully.")
                return True

        print(f"No permission found with title: {title}")
        return False

    def manage_permission_policies(self, perm_title):
        """Manage policies for a specific permission."""
        # Find the permission
        perm = None
        for p in self.permissions:
            if p["title"] == perm_title:
                perm = p
                break

        if not perm:
            print(f"No permission found with title: {perm_title}")
            return False

        while True:
            print(f"\n--- Managing Policies for Permission: {perm_title} ---")
            print("Current policies:")
            if not perm["policies"]:
                print("  No policies assigned")
            else:
                for policy_id in perm["policies"]:
                    policy_obj = None
                    for pol in self.policies:
                        if pol["id"] == policy_id:
                            policy_obj = pol
                            break
                    if policy_obj:
                        print(f"  - {policy_obj['title']} (ID: {policy_id})")
                    else:
                        print(f"  - [Missing Policy: {policy_id}]")

            print("\nOptions:")
            print("1. List available policies to add")
            print("2. Add a policy")
            print("3. Remove a policy")
            print("4. Back")

            choice = input("Enter your choice (1-4): ").strip()

            if choice == "1":
                # List policies not yet assigned to this permission
                available_policies = [
                    p for p in self.policies if p["id"] not in perm["policies"]
                ]
                if not available_policies:
                    print("No policies available to add.")
                else:
                    print("\nAvailable policies to add:")
                    for i, policy in enumerate(available_policies):
                        print(f"  {i + 1}. {policy['title']} (ID: {policy['id']})")
            elif choice == "2":
                # Add a policy
                available_policies = [
                    p for p in self.policies if p["id"] not in perm["policies"]
                ]
                if not available_policies:
                    print("No policies available to add.")
                    continue

                print("\nAvailable policies to add:")
                for i, policy in enumerate(available_policies):
                    print(f"  {i + 1}. {policy['title']}")

                try:
                    selection = int(input("Select a policy to add (number): ")) - 1
                    if 0 <= selection < len(available_policies):
                        selected_policy_id = available_policies[selection]["id"]
                        perm["policies"].append(selected_policy_id)
                        self.update_permission_policies(perm_title, perm["policies"])
                        # Refresh the permission object after update
                        for p in self.permissions:
                            if p["title"] == perm_title:
                                perm = p
                                break
                        print(
                            f"Policy '{available_policies[selection]['title']}' added to permission '{perm_title}'."
                        )
                    else:
                        print("Invalid selection.")
                except ValueError:
                    print("Please enter a valid number.")
            elif choice == "3":
                # Remove a policy
                if not perm["policies"]:
                    print("No policies to remove.")
                    continue

                # Get the policy objects for the permission's policies
                assigned_policies = []
                for pid in perm["policies"]:
                    for pol in self.policies:
                        if pol["id"] == pid:
                            assigned_policies.append(pol)
                            break

                print("\nPolicies assigned to this permission:")
                for i, policy in enumerate(assigned_policies):
                    print(f"  {i + 1}. {policy['title']}")

                try:
                    selection = int(input("Select a policy to remove (number): ")) - 1
                    if 0 <= selection < len(assigned_policies):
                        selected_policy_id = assigned_policies[selection]["id"]
                        perm["policies"].remove(selected_policy_id)
                        self.update_permission_policies(perm_title, perm["policies"])
                        # Refresh the permission object after update
                        for p in self.permissions:
                            if p["title"] == perm_title:
                                perm = p
                                break
                        print(
                            f"Policy '{assigned_policies[selection]['title']}' removed from permission '{perm_title}'."
                        )
                    else:
                        print("Invalid selection.")
                except ValueError:
                    print("Please enter a valid number.")
            elif choice == "4":
                break
            else:
                print("Invalid choice. Please select 1-4.")

    # Policies operations
    def read_all_policies(self):
        """Display all policies."""
        print("\n--- All Policies ---")
        if not self.policies:
            print("No policies found.")
            return
        for policy in self.policies:
            print(f"ID: {policy['id']}")
            print(f"Title: {policy['title']}")
            print(f"Description: {policy['description']}")
            print(f"Created At: {policy['created_at']}")
            print(f"Updated At: {policy['updated_at']}")
            print("---")

    def read_policy_by_title(self, title):
        """Find and display a specific policy by title."""
        for policy in self.policies:
            if policy["title"] == title:
                print("\n--- Policy Details ---")
                print(f"ID: {policy['id']}")
                print(f"Title: {policy['title']}")
                print(f"Description: {policy['description']}")
                print(f"Created At: {policy['created_at']}")
                print(f"Updated At: {policy['updated_at']}")
                return policy
        print(f"No policy found with title: {title}")
        return None

    def create_policy(self, title, description):
        """Create a new policy."""
        current_time = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
        new_policy = {
            "id": self.generate_id(),
            "title": title,
            "description": description,
            "created_at": current_time,
            "updated_at": current_time,
        }

        self.policies.append(new_policy)
        self.save_policies(self.policies)
        self.sync_python_files()
        print(f"Policy '{title}' created successfully with ID: {new_policy['id']}")
        return True

    def update_policy(self, title, new_title=None, description=None):
        """Update an existing policy."""
        for i, policy in enumerate(self.policies):
            if policy["title"] == title:
                if new_title is not None:
                    policy["title"] = new_title
                if description is not None:
                    policy["description"] = description

                policy["updated_at"] = datetime.now().strftime(
                    "%Y-%m-%dT%H:%M:%SZ"
                )  # Update timestamp
                self.policies[i] = policy
                self.save_policies(self.policies)
                self.sync_python_files()
                print(f"Policy with title '{title}' updated successfully.")
                return True

        print(f"No policy found with title: {title}")
        return False

    def delete_policy(self, title):
        """Delete a policy by title."""
        for i, policy in enumerate(self.policies):
            if policy["title"] == title:
                # Get the ID to remove from permissions
                policy_id = policy["id"]
                # Remove this policy from any permissions that reference it
                current_time = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
                for perm in self.permissions:
                    if policy_id in perm["policies"]:
                        perm["policies"].remove(policy_id)
                        perm["updated_at"] = (
                            current_time  # Update the permission's timestamp
                        )

                del self.policies[i]
                self.save_policies(self.policies)
                self.save_permissions(
                    self.permissions
                )  # Save permissions as well due to updates
                self.sync_python_files()
                print(f"Policy with title '{title}' deleted successfully.")
                return True

        print(f"No policy found with title: {title}")
        return False

    def display_menu(self):
        """Display the main menu."""
        print("\n" + "=" * 50)
        print("AUTHORIZATION MANAGEMENT SYSTEM")
        print("=" * 50)
        print("Select an option:")
        print("1. Permissions")
        print("2. Policies")
        print("3. Sync Python Files")
        print("4. Exit")
        print("=" * 50)

    def display_permissions_menu(self):
        """Display the permissions submenu."""
        print("\n--- PERMISSIONS MENU ---")
        print("1. Read All Permissions")
        print("2. Read One Permission")
        print("3. Create Permission")
        print("4. Update Permission")
        print("5. Manage Permission Policies")
        print("6. Delete Permission")
        print("7. Back to Main Menu")
        print("-" * 30)

    def display_policies_menu(self):
        """Display the policies submenu."""
        print("\n--- POLICIES MENU ---")
        print("1. Read All Policies")
        print("2. Read One Policy")
        print("3. Create Policy")
        print("4. Update Policy")
        print("5. Delete Policy")
        print("6. Back to Main Menu")
        print("-" * 30)

    def handle_permissions_menu(self):
        """Handle the permissions submenu."""
        while True:
            self.display_permissions_menu()
            choice = input("Enter your choice (1-7): ").strip()

            if choice == "1":
                self.read_all_permissions()
            elif choice == "2":
                title = input("Enter permission title: ").strip()
                self.read_permission_by_title(title)
            elif choice == "3":
                title = input("Enter permission title: ").strip()
                description = input("Enter permission description: ").strip()
                self.create_permission(title, description, [])
            elif choice == "4":
                old_title = input("Enter permission title to update: ").strip()
                # Get current permission details to display them
                current_perm = None
                for perm in self.permissions:
                    if perm["title"] == old_title:
                        current_perm = perm
                        break

                if current_perm is None:
                    print(f"No permission found with title: {old_title}")
                    continue

                print("Leave fields empty to keep current values")
                new_title = input(
                    f"New title (current: {current_perm['title']}): "
                ).strip()
                new_desc = input(
                    f"New description (current: {current_perm['description']}): "
                ).strip()
                new_policies = input(
                    "New policy IDs (comma-separated, or press Enter to keep current): "
                ).strip()

                new_title = new_title if new_title else None
                description = new_desc if new_desc else None
                policy_ids = (
                    [pid.strip() for pid in new_policies.split(",")]
                    if new_policies
                    else None
                )

                if policy_ids == []:  # If user entered empty, keep current policies
                    policy_ids = None

                self.update_permission(old_title, new_title, description)
            elif choice == "5":
                # Manage Permission Policies - List all available permissions first
                print("\n--- Available Permissions ---")
                if not self.permissions:
                    print("No permissions available.")
                else:
                    for i, perm in enumerate(self.permissions):
                        print(f"{i + 1}. {perm['title']}")

                if self.permissions:
                    selection = input(
                        "Select a permission to manage policies (number) or enter title directly: "
                    ).strip()
                    try:
                        # If selection is a number, get the title from the list
                        index = int(selection) - 1
                        if 0 <= index < len(self.permissions):
                            perm_title = self.permissions[index]["title"]
                        else:
                            print("Invalid selection.")
                            continue
                    except ValueError:
                        # If not a number, treat as a direct title input
                        perm_title = selection
                    self.manage_permission_policies(perm_title)
                else:
                    print("Cannot manage policies: No permissions available.")
            elif choice == "6":
                title = input("Enter permission title to delete: ").strip()
                self.delete_permission(title)
            elif choice == "7":
                break
            else:
                print("Invalid choice. Please select 1-7.")

    def handle_policies_menu(self):
        """Handle the policies submenu."""
        while True:
            self.display_policies_menu()
            choice = input("Enter your choice (1-6): ").strip()

            if choice == "1":
                self.read_all_policies()
            elif choice == "2":
                title = input("Enter policy title: ").strip()
                self.read_policy_by_title(title)
            elif choice == "3":
                title = input("Enter policy title: ").strip()
                description = input("Enter policy description: ").strip()
                self.create_policy(title, description)
            elif choice == "4":
                old_title = input("Enter policy title to update: ").strip()
                # Get current policy details to display them
                current_policy = None
                for policy in self.policies:
                    if policy["title"] == old_title:
                        current_policy = policy
                        break

                if current_policy is None:
                    print(f"No policy found with title: {old_title}")
                    continue

                print("Leave fields empty to keep current values")
                new_title = input(
                    f"New title (current: {current_policy['title']}): "
                ).strip()
                new_desc = input(
                    f"New description (current: {current_policy['description']}): "
                ).strip()

                new_title = new_title if new_title else None
                description = new_desc if new_desc else None

                self.update_policy(old_title, new_title, description)
            elif choice == "5":
                title = input("Enter policy title to delete: ").strip()
                self.delete_policy(title)
            elif choice == "6":
                break
            else:
                print("Invalid choice. Please select 1-6.")

    def run(self):
        """Run the CLI application."""
        print("Welcome to the Authorization Management System!")

        while True:
            self.display_menu()
            choice = input("Enter your choice (1-4): ").strip()

            if choice == "1":
                self.handle_permissions_menu()
            elif choice == "2":
                self.handle_policies_menu()
            elif choice == "3":
                self.sync_python_files()
            elif choice == "4":
                print("Thank you for using Authorization Management System!")
                break
            else:
                print("Invalid choice. Please select 1-4.")


def main():
    manager = AuthManager()
    manager.run()


if __name__ == "__main__":
    main()
