"""
Use Cases module - Clean Architecture implementation.
All use cases are independent of frameworks and external concerns.
"""

# User use cases
from .user import (
    AssignRoleRequest,
    AssignRoleResponse,
    AssignRoleToUserUseCase,
    CreateUserRequest,
    CreateUserResponse,
    CreateUserUseCase,
    DeleteUserRequest,
    DeleteUserResponse,
    DeleteUserUseCase,
    GetAllUsersRequest,
    GetAllUsersResponse,
    GetAllUsersUseCase,
    GetUserByIdRequest,
    GetUserByIdResponse,
    GetUserByIdUseCase,
    RemoveRoleFromUserUseCase,
    RemoveRoleRequest,
    RemoveRoleResponse,
    UpdateUserRequest,
    UpdateUserResponse,
    UpdateUserUseCase,
)

# Auth use cases
from .auth import (
    AuthenticateUserUseCase,
    ITokenService,
    IPasswordService,
    LoginRequest,
    LoginResponse,
    LoginUseCase,
    LogoutRequest,
    LogoutResponse,
    LogoutUseCase,
    RefreshAccessTokenUseCase,
    RefreshTokenRequest,
    RefreshTokenResponse,
    TokenResponse,
)

# Role use cases
from .role import (
    AssignPermissionRequest,
    AssignPermissionResponse,
    AssignPermissionToRoleUseCase,
    CreateRoleRequest,
    CreateRoleResponse,
    CreateRoleUseCase,
    DeleteRoleRequest,
    DeleteRoleResponse,
    DeleteRoleUseCase,
    GetAllRolesRequest,
    GetAllRolesResponse,
    GetAllRolesUseCase,
    GetRoleByIdRequest,
    GetRoleByIdResponse,
    GetRoleByIdUseCase,
    RemovePermissionRequest,
    RemovePermissionResponse,
    RemovePermissionFromRoleUseCase,
    UpdateRoleRequest,
    UpdateRoleResponse,
    UpdateRoleUseCase,
)

# Permission use cases
from .permission import (
    GetAllPermissionsRequest,
    GetAllPermissionsResponse,
    GetAllPermissionsUseCase,
    GetPermissionByIdRequest,
    GetPermissionByIdResponse,
    GetPermissionByIdUseCase,
    GetPermissionByTitleRequest,
    GetPermissionByTitleResponse,
    GetPermissionByTitleUseCase,
    SearchPermissionsRequest,
    SearchPermissionsResponse,
    SearchPermissionsUseCase,
)

# Policy use cases
from .policy import (
    GetAllPoliciesRequest,
    GetAllPoliciesResponse,
    GetAllPoliciesUseCase,
    GetPolicyByIdRequest,
    GetPolicyByIdResponse,
    GetPolicyByIdUseCase,
    GetPolicyByTitleRequest,
    GetPolicyByTitleResponse,
    GetPolicyByTitleUseCase,
    SearchPoliciesRequest,
    SearchPoliciesResponse,
    SearchPoliciesUseCase,
)

# Policy engine use cases
from .policy_engine import (
    EvaluatePoliciesRequest,
    EvaluatePoliciesResponse,
    EvaluatePoliciesUseCase,
)

__all__ = [
    # User use cases
    "GetAllUsersUseCase",
    "GetAllUsersRequest",
    "GetAllUsersResponse",
    "GetUserByIdUseCase",
    "GetUserByIdRequest",
    "GetUserByIdResponse",
    "CreateUserUseCase",
    "CreateUserRequest",
    "CreateUserResponse",
    "UpdateUserUseCase",
    "UpdateUserRequest",
    "UpdateUserResponse",
    "DeleteUserUseCase",
    "DeleteUserRequest",
    "DeleteUserResponse",
    "AssignRoleToUserUseCase",
    "AssignRoleRequest",
    "AssignRoleResponse",
    "RemoveRoleFromUserUseCase",
    "RemoveRoleRequest",
    "RemoveRoleResponse",
    # Auth use cases
    "AuthenticateUserUseCase",
    "LoginUseCase",
    "LoginRequest",
    "LoginResponse",
    "RefreshAccessTokenUseCase",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "LogoutUseCase",
    "LogoutRequest",
    "LogoutResponse",
    "TokenResponse",
    "IPasswordService",
    "ITokenService",
    # Role use cases
    "GetAllRolesUseCase",
    "GetAllRolesRequest",
    "GetAllRolesResponse",
    "GetRoleByIdUseCase",
    "GetRoleByIdRequest",
    "GetRoleByIdResponse",
    "CreateRoleUseCase",
    "CreateRoleRequest",
    "CreateRoleResponse",
    "UpdateRoleUseCase",
    "UpdateRoleRequest",
    "UpdateRoleResponse",
    "DeleteRoleUseCase",
    "DeleteRoleRequest",
    "DeleteRoleResponse",
    "AssignPermissionToRoleUseCase",
    "AssignPermissionRequest",
    "AssignPermissionResponse",
    "RemovePermissionFromRoleUseCase",
    "RemovePermissionRequest",
    "RemovePermissionResponse",
    # Permission use cases
    "GetAllPermissionsUseCase",
    "GetAllPermissionsRequest",
    "GetAllPermissionsResponse",
    "GetPermissionByIdUseCase",
    "GetPermissionByIdRequest",
    "GetPermissionByIdResponse",
    "GetPermissionByTitleUseCase",
    "GetPermissionByTitleRequest",
    "GetPermissionByTitleResponse",
    "SearchPermissionsUseCase",
    "SearchPermissionsRequest",
    "SearchPermissionsResponse",
    # Policy use cases
    "GetAllPoliciesUseCase",
    "GetAllPoliciesRequest",
    "GetAllPoliciesResponse",
    "GetPolicyByIdUseCase",
    "GetPolicyByIdRequest",
    "GetPolicyByIdResponse",
    "GetPolicyByTitleUseCase",
    "GetPolicyByTitleRequest",
    "GetPolicyByTitleResponse",
    "SearchPoliciesUseCase",
    "SearchPoliciesRequest",
    "SearchPoliciesResponse",
    # Policy engine use cases
    "EvaluatePoliciesUseCase",
    "EvaluatePoliciesRequest",
    "EvaluatePoliciesResponse",
]
